# Usuário e senha de conexão com o banco de dados
spring:
  datasource:
    username: user
    password: password
    url: jdbc:mysql://localhost:3306/db?allowPublicKeyRetrieval=true&rewriteBatchedStatements=true&useSSL=false&useUnicode=yes&characterEncoding=UTF-8&useLegacyDatetimeCode=true&createDatabaseIfNotExist=true&useTimezone=true&serverTimezone=UTC

  # Apontamos para o JPA e Hibernate qual é o dialeto do banco de dados
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    database-platform: org.hibernate.dialect.MySQL8Dialect

    # Deixamos o Hibernate responsável por ler nossas entidades e criar as tabelas do nosso banco de dados automaticamente
    hibernate:
      ddl-auto: create

    # Configuração do Hibernate para reconhecer o nome de tabelas em caixa alta
    naming:
      physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    # Configurações de log
    show-sql: true
  security:
    basic.enable: false
  springdoc.swagger-ui.path: /swagger-ui.html